# Generated by Django 3.2.25 on 2025-09-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
