# Generated by Django 3.2.25 on 2025-09-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_productvariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
